### ISSUE TITLE
Bug no Login

### ISSUE THREAD

**Issue by achilesmatheus** [uitanmaciel/IbgeAPI#1]
Bom dia. Tem que fazer uma correção no login. 

Quando o método Login da UserService chama a função `_userRepository.GetByEmailAsync(user.Email.Address)`, aparece um erro no debug.

```c#
public async Task<IResult> Login(Models.User user)
    {
        try
        {
            var userDb = await _userRepository.GetByEmailAsync(user.Email.Address);
            if (userDb == null || !BCrypt.Net.BCrypt.Verify(user.Password.Keyword, userDb.Password.Keyword))
                throw new Exception("User Unauthorized. Invalid email or password.");

            var token = AuthenticationService.GenerateToken(user);
            return Results.Ok(token);
        }
        catch (System.Exception)
        {            
            return Results.BadRequest();
        }
    }
```

```c#
public async Task<Models.User> GetByEmailAsync(string email)
    {
        return await _context.Users.AsNoTracking().SingleOrDefaultAsync(x => x.Email.Address == email);
    }  
```

Identifiquei que você está utilizando `SingleOrDefaultAsync`. Porém essa função lança uma exception quando há dois ou mais registros no banco com o mesmo email. 

Temos que definir o campo email no banco como INDEX UNIQUE para evitar cadastro de dois emails iguais. Dessa forma, resolve.

Obs: Por algum motivo desconhecido, mesmo lançando uma exceção, a requisição retorna status code 200. Estranho

**Comment by uitanmaciel** [comment]
Testei aqui com um usuário possuindo e-mails duplicados. Não apresentou nenhuma exception. Pode printar a tela do erro que está aparecendo para você?

**Comment by achilesmatheus** [comment]
A exception é lançada no modo debug. Mais tarde te envio um print
