### ISSUE TITLE
Imutabilidade dos Value Objects

### ISSUE THREAD

**Issue by achilesmatheus** [uitanmaciel/IbgeAPI#3]
Nossas classes `Email` e `Password` precisam ser imutáveis, senão isso foge do conceito de value objects.

Sugiro privar o `set` ou removê-lo.

`Models/ValueObjects/Email.cs`
```c#
public class Email
{
    public string Address { get; private set; } = null!; // Adicionado o private

    public Email() { }
    
    public Email(string address)
    {
        Address = address;        
    }    
}
```

**Referência**: [Value Objects e Entity Framework](https://balta.io/blog/ef-core-value-objects)

**Comment by uitanmaciel** [comment]
Resolvido.
